name: Automatic Publication

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  validate-and-publish:
    name: Validate and Publish to TR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-web-perf/2021Apr/0005.html
          W3C_BUILD_OVERRIDE: |
            Status: WD
